<?php

/**
 * @file
 * Contains openteam_helper.module.
 */

/**
 * Implements hook_theme().
 */
function dc_stats_theme() {
  return [
    'dc_stats' => [
      'variables' => [
        'id' => NULL,
        'content' => NULL,
        'title' => NULL,
        'rec' => NULL,
        'yds' => NULL,
        'tds' => NULL,
        'int' => NULL,
        'att' => NULL,
        'avg' => NULL,
        'body' => NULL,
      ],
    ],
  ];
}
